baseurl: "https://www.bufferbloat.net/projects/"
languageCode: "en-us"
title: "Bufferbloat.net"
disable404: false
relativeURLs: false
pluralizeListTitles: false
metadataFormat: yaml
params:
  stylesheets: [ "bootstrap.css", "font-awesome.css", "custom.css" ]
author:
  name: The Bufferbloat community
  email: bloat@lists.bufferbloat.net

